version: '3'

services:
  php:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sequia
      POSTGRES_USER: sequia
      POSTGRES_PASSWORD: sequia
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@sequia.com.ar
      PGADMIN_DEFAULT_PASSWORD: sequia
    ports:
      - "5050:80"

  geoserver:
    image: kartoza/geoserver
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=sequia
      - DATABASE_USER=sequia
      - DATABASE_PASSWORD=sequia
    depends_on:
      - postgres
    volumes:
      - ./data/geoserver:/opt/geoserver/data_dir

  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_DB: sequia
      POSTGRES_USER: sequia
      POSTGRES_PASSWORD: sequia
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data

  gdal:
    image: osgeo/gdal:alpine-small-3.6.3
    volumes:
      - ./:/mnt
