version: '3'
volumes:
    postgres-data:
      driver: local
    geoserver-data:
      driver: local
networks:
  backend:
services:
  php:
    image: php:8.2-apache
    build:
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_DB: sequia
      POSTGRES_USER: sequia
      POSTGRES_PASSWORD: sequia
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend      

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: info@sequia.com.ar
      PGADMIN_DEFAULT_PASSWORD: sequia
    ports:
      - "5050:80"

  geoserver:
    image: kartoza/geoserver:2.22.2
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=sequia
      - DATABASE_USER=sequia
      - DATABASE_PASSWORD=sequia
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - USE_DEFAULT_CREDENTIALS=true
# Datos de conexión a GeoServer
#      - GEOSERVER_ADMIN_USER=admin
#      - GEOSERVER_ADMIN_PASSWORD=geoserver
    depends_on:
      - postgres
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    networks:
      - backend
